# baima tongling
# topic0: &topic0 "/front/rslidar_points"
# topic1: &topic1 "/front_left/rslidar_points"
# topic2: &topic2 "/front_right/rslidar_points"
# topic3: &topic3 "/back/rslidar_points"

# ruomaoshan
# topic1: &topic1 "/front_left/rslidar_points"
# topic2: &topic2 "/front_right/rslidar_points"
# topic3: &topic3 "/back/rslidar_points"

# chongqing
# topic0: &topic0 "/front_lidar"
# topic1: &topic1 "/front_left_lidar"
# topic2: &topic2 "/front_right_lidar"
# topic3: &topic3 "/back_lidar"

bag0: &bag0 "lidar_front.bag"
bag1: &bag1 "lidar_back.bag"


# lidar_topics: &lidar_topics_all [*topic0, *topic1, *topic2, *topic3]
bag_files: [*bag0, *bag1]

threshold_plane: 0.4

ground_weight_f_l: 1.0
ground_weight_f_r: 1.0
ground_weight_l_r: 1.0
ground_weight_b_l: 1.0
ground_weight_b_r: 1.0

ground_z_threshold: 1.0


pre_mat: [
        -0.00347673,
        -0.999951,
        -0.00929107,
        -0.1,
        0.999994,
        -0.00346313,
        -0.0014848,
        7.6564,
        0.00145256,
        -0.00929617,
        0.999956,
        0.1,
        0,
        0,
        0,
        1
]




      