# baima tongling
# topic0: &topic0 "/front/rslidar_points"
# topic1: &topic1 "/front_left/rslidar_points"
# topic2: &topic2 "/front_right/rslidar_points"
# topic3: &topic3 "/back/rslidar_points"

# ruomaoshan
# topic1: &topic1 "/front_left/rslidar_points"
# topic2: &topic2 "/front_right/rslidar_points"
# topic3: &topic3 "/back/rslidar_points"

# chongqing
topic0: &topic0 "/front_lidar"
topic1: &topic1 "/front_left_lidar"
topic2: &topic2 "/front_right_lidar"
topic3: &topic3 "/back_lidar"

bag0: &bag0 "lidar_front.bag"
bag1: &bag1 "lidar_back.bag"
bag_files: [*bag0, *bag1]

# 话题排列顺序，四激光：前左右后 三激光：左右后
lidar_topics: &lidar_topics_all [*topic0, *topic1, *topic2, *topic3]

# 如果 launch 里的 recalibration_mode 为假， 重新标定所有激光雷达，否则 调整聚光雷达的方案

# 全部重新标定方案
front_lidar_height: 1.2

# 调整聚光雷达的方案, 需要填写下面的所有的位置
fix_front: true
front_pose: [
        0.020842673,
        -0.99976414,
        0.0062025213,
        -0.09032783,
        0.99614,
        0.020237269,
        -0.085412592,
        7.788188,
        0.085266851,
        0.0079588043,
        0.99632621,
        0.24670997,
        0,
        0,
        0,
        1
]

fix_left: false
left_pose: [
    -0.9998,  -0.0074627,   -0.018576,    -3.06486, 
 0.00752983,   -0.999965, -0.00354314,     5.54761, 
 -0.0185489, -0.00368281,    0.999821,     2.09396, 
          0,           0,           0,           1
]

fix_right: false
right_pose: [
        0.999722,  0.00344381,  -0.0233651,     2.78645, 
        -0.00320187,    0.999941,   0.0103893,     5.31634, 
        0.0233994,  -0.0103116,    0.999672,      2.0776, 
        0,           0,           0,           1
]

fix_back: false
back_pose: [
        -0.040605687,
        0.99885064,
        0.0254869,
        -0.2027536459,
        -0.9990738,
        -0.040951289,
        0.013185005,
        -0.44418994,
        0.01421359,
        -0.024927812,
        0.99958813,
        0.86045597,
        0,
        0,
        0,
        1
]
