# baima tongling
# topic0: &topic0 "/front/rslidar_points"
# topic1: &topic1 "/front_left/rslidar_points"
# topic2: &topic2 "/front_right/rslidar_points"
# topic3: &topic3 "/back/rslidar_points"

# ruomaoshan
# topic1: &topic1 "/front_left/rslidar_points"
# topic2: &topic2 "/front_right/rslidar_points"
# topic3: &topic3 "/back/points"

# chongqing
topic0: &topic0 "/front_lidar"
topic1: &topic1 "/front_left_lidar"
topic2: &topic2 "/front_right_lidar"
topic3: &topic3 "/back_lidar"

bag0: &bag0 "lidar_front.bag"
bag1: &bag1 "lidar_back.bag"
bag_files: [*bag0, *bag1]

# 话题排列顺序，四激光：前左右后 三激光：左右后
lidar_topics: &lidar_topics_all [*topic0, *topic1, *topic2, *topic3]
# lidar_topics: &lidar_topics_all [*topic1, *topic2, *topic3]

# 如果 launch 里的 recalibration_mode 为假， 重新标定所有激光雷达，否则 调整聚光雷达的方案

# 全部重新标定方案
front_lidar_height: 1.2

# 调整聚光雷达的方案, 需要填写下面的所有的位置
fix_front: false
front_pose: [
 0.0202937,  -0.999622, -0.0185641, -0.0841609, 
  0.999543,  0.0207014, -0.0220379,    7.78815, 
 0.0224138, -0.0181084,   0.999585,   0.522669, 
         0,          0,          0,          1
]

fix_left: true
left_pose: [
        -0.999268, -0.0313249, -0.0219625,   -3.13494, 
        0.0293781,  -0.996035,  0.0839667,    5.72013, 
        -0.0245057,    0.08326,   0.996226,    2.33457, 
                0,          0,          0,          1
]

fix_right: true
right_pose: [
        0.998815,  0.00723224,  -0.0481223,     2.73855, 
        -0.00419909,    0.998015,   0.0628352,     5.84418, 
        0.0484812,  -0.0625587,    0.996863,     2.42325, 
                0,           0,           0,           1
]

fix_back: true
back_pose: [
 -0.0204848,     0.99978,  0.00451732,   -0.107299, 
  -0.998236,  -0.0207046,   0.0556518,   -0.420217, 
  0.0557331, -0.00336933,     0.99844,     1.64536, 
          0,           0,           0,           1
]
